substitutions:
  _REGION: asia-southeast2
  _REPO:   moneylion-202511010
  _IMAGE:  loan-default-api

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
    - -c
    - |
      docker buildx create --use
      docker buildx build \
        --platform linux/amd64 \
        -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${COMMIT_SHA} \
        -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest \
        --push --load .

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_IMAGE}
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${COMMIT_SHA}
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --memory=1024Mi

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${COMMIT_SHA}'


options:
  logging: CLOUD_LOGGING_ONLY